name: Build and Deploy

on:
  push:
    branches:
      ["master"]


env:
  CARGO_TERM_COLOR: always


jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build
        run: |
          wasm-pack build --target web
          mkdir dist
          mkdir dist/src
          npm i -g terser
          terser pkg/snake_game.js --compress --mangle -o dist/src/snake_game.min.js 
          mv pkg/snake_game.js dist/src/
          mv pkg/snake_game_bg.wasm dist/src/
          cp -r assets dist/
          cat > dist/index.html <<EOL
          <html lang="en">
            <head>
              <title>Snake game</title>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1">
            </head>
            <body>
              <script type="module">
                import init from "./src/snake_game.min.js";
                init()
              </script>
            </body>
          </html>
          EOL
          cat > dist/README.md <<EOL
          # About
          This is the compiled and previewable version of [snake game](https://github.com/a-rustacean/snake-game) made by [dilshad](https://github.com/a-rustacean). Try it [here](https://a-rustacean.github.io/snake-game)
          EOL
          cp LICENSE dist/
          tree dist

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
